### ISSUE TITLE
No flash message on create with errors

### ISSUE THREAD

**Issue by cj** [activeadmin/inherited_resources#217]
Hi,

When submitting a form with errors, no flash message is sent back... but when I update a form with no errors it gives me the success flash message....

```
    inherited_resources (1.3.0)
      has_scope (~> 0.5.0)
      responders (~> 0.6.0)
```

Any ideas on why this would happen?

**Comment by cj** [comment]
ah looks like I just needed to do:

```
en:
  flash:
    actions:
      create:
        alert: "There were issues creating the %{resource_name}."
```

Strange this isn't there by default.
